### ISSUE TITLE
php artisan db:seed

### ISSUE THREAD

**Issue by qbmiller** [baijunyao/laravel-bjyblog#11]
composer update/install
php artisan key:generate  生成随机key
改好env 后,数据库地址账号密码
php artisan migrate
上边都做完后 , 不执行生成随机数据的话,  直接访问 会报错, cache  [ php artisan db:seed ]
![image](https://user-images.githubusercontent.com/7335567/35785754-e39397a4-0a5d-11e8-802f-d53230ab78f2.png)

**Comment by baijunyao** [comment]
需要从数据库读取配置项；所以必须执行数据填充；参考使用说明  https://baijunyao.com/article/129
