### ISSUE TITLE
申请友链存在xss漏洞

### ISSUE THREAD

**Issue by thiscodecc** [baijunyao/laravel-bjyblog#118]
在前台申请友链的时候在url地址输入**javascript:alert('xss');//http**
<img width="1241" alt="1001" src="https://user-images.githubusercontent.com/55778895/66316874-02c82180-e94b-11e9-9a21-951abdce8714.png">

在后台查看的时候.点击这个url就会触发.
<img width="1172" alt="10002" src="https://user-images.githubusercontent.com/55778895/66317300-d1038a80-e94b-11e9-83fe-dff71ee71589.png">

<img width="733" alt="10003" src="https://user-images.githubusercontent.com/55778895/66317327-dfea3d00-e94b-11e9-8968-35062e66ad7d.png">

```
public function setUrlAttribute($value)
    {
        // 如果没有http 则补上http
        if (strpos($value, 'http') === false) {
            $value = 'http://' . $value;
        }

        $this->attributes['url'] = strtolower(rtrim($value, '/'));
    }
```

代码里判断URL时,只判断了字符串里面是否有http,没有则在开头位置拼接http。
没有判断字符串在http的位置,**javascript:alert('xss');//http** 那这样就绕过了,应该判断http要在字符串开始位置出现.

**Comment by baijunyao** [comment]
多谢反馈； 如果管理员在后台点击有问题的 URL 确实会被攻击； 修复了哈；
