### ISSUE TITLE
mix doesn't resolve path

### ISSUE THREAD

**Issue by neapolis79** [baijunyao/laravel-bjyblog#122]
i have installed all packages and dipendencies with composer update, and after that, i installated the frontend libraries with npm install and  npm run dev
After all this resource projects are not avalaible becase laravel mix doesn't convert the resource path.
So this instruction doesn't work 
<script src="{{ mix('js/admin.js') }}"></script> 
I had to change it to 
<script src="{{ asset('js/admin.js') }}"></script>

this in both the admin and home templates

This happen only to me?

**Comment by baijunyao** [comment]
What is your link?  
![image](https://user-images.githubusercontent.com/9360694/67498613-50b28880-f6b2-11e9-8966-f238c9d3e26b.png)

- Check for an error message on the command line?
- Are there any CSS and JS files in the public directory?

![image](https://user-images.githubusercontent.com/9360694/67499072-0978c780-f6b3-11e9-83ea-e1e4a5594192.png)

**Comment by neapolis79** [comment]
Hi, 
yes in my public folder i have all the correct file, and no error when i compile or launch the run dev command
![public](https://user-images.githubusercontent.com/36012957/67516874-ac284a80-f6a1-11e9-9535-a126622e2d12.PNG)

in my case i put the web application in a subfolder of localhost, so my base url is "_http://localhost/laravel-bjyblog_" 

with laravel mix the resource path in output are similar to "_http://localhost/js/admin.js?id=b38d4123bc8c65d05c83_" so no subfolder in the path

if i use _asset_ command instead of _mix_ the laravel create the correct path that include the subfolder, but the internal link of js and css are wrong (link to fontawesome for example are unreachable)
If i use in webpack the command
mix.setResourcePath("../"); with the asset command i finally have the correct path for css and for the internal link like fontawesome or gliphyicon, but the path to other resource like uploads are wrong.

In any case i have to rework on the resource or the css, so what i'm asking is if there is something (istruction, configuration or other stuff) that i'm missing to make it all work.

**Comment by baijunyao** [comment]
You should set the application root to `/laravel-bjyblog/public` ;  
If you use Nginx then the configuration should look like this:
```
server {
    listen 80;
    server_name baijunyao.com;
    root /var/www/laravel-bjyblog/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```
Please note that you need to replace it with your own:
```
    server_name baijunyao.com;
    root /var/www/laravel-bjyblog/public;
```

doc: [https://laravel.com/docs/6.x/deployment](https://laravel.com/docs/6.x/deployment)

**Comment by neapolis79** [comment]
hi use a XAMPP stack for developing, so following your suggestion i restore all the original configuration and then worked on the server side so now i resolved in this way (i wrote here for others with my same problem)

1) first of all i created a virtual host on my server adding to my "_httpd-vhosts.conf_" (in my case located at "C:\xampp\apache\conf\extra\")

```
<Directory C:/xampp/htdocs/laravel-bjyblog>
    AllowOverride All
    Require all granted
</Directory>

<VirtualHost *:80>
    DocumentRoot "C:/xampp/htdocs/laravel-bjyblog/public"
    ServerName bjyblog.localhost
</VirtualHost>

```

2) then i added my hosts file (in my case located at _C:\Windows\System32\drivers\etc\hosts_ )

`127.0.0.1                   bjyblog.localhost`

3) so now my application works fine to http://bjyblog.localhost`

done.
So sorry to disturb you for this and thanks for the helping

**Comment by baijunyao** [comment]
Very good, thank you, if you have any questions during the use, you can open an issue at any time.
