### ISSUE TITLE
Is it possible to add a little sociality to the blog?

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#126]
Dear Junyao Bai!
If possible, could you integrate such functionality for your system?
https://github.com/cybercog/laravel-love
Documentation here https://laravel-love.readme.io/docs
If this is not possible, could you please implement the simplest dislike likes system for posts and comments?
Thanks.

**Comment by baijunyao** [comment]
No problem. I'll do that later.

**Comment by baijunyao** [comment]
The like feature has been completed, you can pull the latest code to use it.
![QQ20191214-130651](https://user-images.githubusercontent.com/9360694/70844408-a964fd00-1e7b-11ea-9620-7b318dead67c.png)

**Comment by yuri25** [comment]
Hi, this works.
Can you find out if this is your development or some third-party package was used?
Thank you very much!

**Comment by baijunyao** [comment]
I used this package. https://github.com/overtrue/laravel-follow    
The advantage of this package is that it will create a new database table without modifying the existing database table.  
And this package has many actions that may be used in the future.

**Comment by yuri25** [comment]
Thank you!
