### ISSUE TITLE
After updating incorrect operation

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#129]
Today I performed as usual:
```
git pull
composer install --no-dev
php artisan bjyblog: update
```
After authorization by the administrator, the name does not appear in the upper right corner as before, as before, only the "login" link is visible.
![tag-2](https://user-images.githubusercontent.com/253228/70377746-34e50800-1929-11ea-830c-35382266c9b7.png)

Although the admin panel is available at / admin
Cleared the site cache - a message about the successful clearing of the cache did not appear.
I tried to write an article, it works more or less, but a new tag was not added, just a window with this tag hangs and that’s it, there is no sending a tag. 

![tag-1](https://user-images.githubusercontent.com/253228/70377784-87bebf80-1929-11ea-9e3f-59da95d18db8.png)

When trying to publish an article, I received the following error:
419|Page is out of date

**Comment by baijunyao** [comment]
I logged in successfully. Do you try again?
![image](https://user-images.githubusercontent.com/9360694/70383423-a87a2a00-19a8-11ea-88cc-74d6f45e1c70.png)

Try the following two ways:
1. Clear cache
```bash
php artisan cache:clear
php artisan config:clear
```
Clear browser cache.
![image](https://user-images.githubusercontent.com/9360694/70383800-c2b70680-19ae-11ea-9f27-21d75470e3a7.png)  
2. Check `.env` file
The `APP_URL` should be `https://xtty.ru`

If it still doesn't work, please let me know, thank you.

**Comment by baijunyao** [comment]
I just added a hotfix commit.   
You need to pull the latest code.   
If you want both  `xtty.ru` and `www.xtty.ru` login in.  
You need to add `SESSION_DOMAIN=.xtty.ru` to `.env` file.

**Comment by yuri25** [comment]
I performed:
```
git pull 
composer install --no-dev
php artisan bjyblog:update
```
Then in the console:
```
php artisan cache:clear
php artisan config:clear
```
Logged in as administrator normally.
Unfortunately, a new tag is not added to the article, the window continues to hang and nothing happens.
The same thing when trying to publish an article writes this:
419|Page is out of date

**Comment by baijunyao** [comment]
Try clear your browser cookies?

**Comment by yuri25** [comment]
Oh, sorry, after clearing the browser cache everything works fine! Thank you very much! You have solved the problem, Respect!
