### ISSUE TITLE
Incorrect break and word wrap

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#130]
Hello. The heading of the article does not correctly break and transfer the word to the next line. Make the correct break and hyphenation is impractical, because the language has a lot of rules and nuances. It is best to solve this problem without breaking the word, but by transferring part of the sentence or the word if it does not fit in the content output field. Those. make a translation based on whole words. Do not divide the words into parts or a certain number of characters, but transfer the whole word or several words.
A similar problem is in the announcements of articles. I attach screenshots for clarity of understanding of the problem. Thank you for your work.

![xtty-1](https://user-images.githubusercontent.com/253228/70534449-233f7280-1b6c-11ea-805b-5586400352d7.png)

It would be right like that:

![xtty-2](https://user-images.githubusercontent.com/253228/70534463-2aff1700-1b6c-11ea-9b71-c654b14b56d9.png)

![xtty-3](https://user-images.githubusercontent.com/253228/70534480-34887f00-1b6c-11ea-89dd-799df174f63a.png)

**Comment by baijunyao** [comment]
Thank you, I already used `break-word` instead of `keep-all`.  
The screenshot below is a problem caused by string interception, I will fix it later.
![image](https://user-images.githubusercontent.com/9360694/70635667-49017000-1c6f-11ea-805a-85d1bd6d0e88.png)

**Comment by yuri25** [comment]
The hyphenation also does not work in the sidebar ... I probably really tired you with my wishes :))
![sidebar-1](https://user-images.githubusercontent.com/253228/71841221-fa10f400-30cf-11ea-9dd9-b220af94f88f.jpg)

**Comment by baijunyao** [comment]
OK, I fixed it.

**Comment by yuri25** [comment]
Updated. Everything works perfectly. Thank you very much!
