### ISSUE TITLE
The update link in the admin panel causes an error

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#133]
In the admin panel there is such an item: blog version - and vice versa v6.7.0 update. If you click on this link, then such a screen appears with an error.
The link leads to such a URL https://xtty.ru/admin/index/upgrade
 In general, I am updating from the console as indicated in your documentation here
https://baijunyao.com/docs/laravel-bjyblog/en/Upgrade.html
I just want to find out why this link is in the admin panel .... maybe you need to configure something? Thanks.

![update-1](https://user-images.githubusercontent.com/253228/71494352-97119880-2857-11ea-9d9b-4bf4c06fa873.jpg)

**Comment by baijunyao** [comment]
This feature is incomplete and I will delete it, updating from the console is correct.
