### ISSUE TITLE
Comments on articles are not added

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#134]
After the last update - comments on articles are not added.

**Comment by baijunyao** [comment]
Thank you, I fixed it, please pull the latest code.

**Comment by yuri25** [comment]
Updated, comments are added. Thanks. If I understand correctly, then comments from the administrator do not appear in the sidebar, are they visible only under the article?

**Comment by baijunyao** [comment]
Yes.

**Comment by yuri25** [comment]
Updated. Everything works perfectly. Thank you very much!
