### ISSUE TITLE
使用 docker-compose up -d 启动，找到不镜像

### ISSUE THREAD

**Issue by thousmile** [baijunyao/laravel-bjyblog#135]
Status: Downloaded newer image for baijunyao/nginx:latest
ERROR: no such image: baijunyao/php:: invalid reference format

![image](https://user-images.githubusercontent.com/28520524/72514491-a0f04f80-3889-11ea-9935-7d00285eb78e.png)

**Comment by baijunyao** [comment]
镜像是有的： https://hub.docker.com/r/baijunyao/php/tags
我刚测了下；可以成功执行；重试下试试？ 

![image](https://user-images.githubusercontent.com/9360694/72515915-bcf4f080-388b-11ea-91d7-4ca784bdf4a2.png)
