### ISSUE TITLE
trans() returns "Target class [translator] does not exist."

### ISSUE THREAD

**Issue by BoGnY** [baijunyao/laravel-bjyblog#138]
Just cloned the `develop` branch, tried to using `trans()`, but it returns `Target class [translator] does not exist.`

It seems that `Overtrue\LaravelLang\TranslationServiceProvider` is not loaded correctly...

**Comment by baijunyao** [comment]
I failed to repeat this error, You can follow the [documentation](https://baijunyao.com/docs/laravel-bjyblog/en/Installation.html), let me know if I still get an error, thank you.

**Comment by BoGnY** [comment]
Sorry @baijunyao, is needed more info:
- followed this instruction: [installation](https://baijunyao.com/docs/laravel-bjyblog/en/Installation.html)
- edit one config file in `config` dir, using `trans()` function (using it in controller is ok)
- running `php artisan serve`
- you get the error

👍

**Comment by baijunyao** [comment]
Yes, you cannot use the `trans()` function in the config file.   
If you want to use `trans()` for config values, you can do it in the `ServiceProvider` file.
For example https://github.com/baijunyao/laravel-bjyblog/blob/3aec01f369de778283222796c0964e038f55066b/app/Providers/ComposerServiceProvider.php#L40-L60

**Comment by BoGnY** [comment]
Thanks 👍
