### ISSUE TITLE
Call to undefined function Intervention\Image\Gd\imagettfbbox()

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#139]
When adding an article with a picture inside, such an error occurred.
`

(1/1) ErrorCall to undefined function Intervention\Image\Gd\imagettfbbox()
--
in Font.php line 86
at Font->getBoxSize()in Font.php line 141
at Font->applyToImage(object(Image), 1574, 896)in TextCommand.php line 30
at TextCommand->execute(object(Image))in AbstractDriver.php line 94
at AbstractDriver->executeCommand(object(Image), 'text', array('XTTY.RU', 1574, 896, object(Closure)))in Image.php line 108
at Image->__call('text', array('XTTY.RU', 1574, 896, object(Closure)))in helpers.php line 32
at add_text_water('/var/www/admin/data/www/xtty.ru/public/uploads/article/20200304/5e5f7c726b6d3.jpg', 'XTTY.RU')in ArticleObserver.php line 51
at ArticleObserver->saving(object(Article), object(Article), null, array(), array())
at call_user_func_array(array(object(ArticleObserver), 'saving'), array(object(Article), 'model' => object(Article), 'relation' => null, 'pivotIds' => array(), 'pivotIdsAttributes' => array()))in Dispatcher.php line 388
at Dispatcher->Illuminate\Events\{closure}('eloquent.saving: App\\Models\\Article', array(object(Article), 'model' => object(Article), 'relation' => null, 'pivotIds' => array(), 'pivotIdsAttributes' => array()))in Dispatcher.php line 218
at Dispatcher->dispatch('eloquent.saving: App\\Models\\Article', array(object(Article), 'model' => object(Article), 'relation' => null, 'pivotIds' => array(), 'pivotIdsAttributes' => array()), true)in Dispatcher.php line 191
at Dispatcher->until('eloquent.saving: App\\Models\\Article', array(object(Article), 'model' => object(Article), 'relation' => null, 'pivotIds' => array(), 'pivotIdsAttributes' => array()))in ExtendFireModelEventTrait.php line 46
at Base->fireModelEvent('saving')in Model.php line 651
at Model->save()in Builder.php line 765
at Builder->Illuminate\Database\Eloquent\{closure}(object(Article))in helpers.php line 422
at tap(object(Article), object(Closure))in Builder.php line 766

`

**Comment by baijunyao** [comment]
You need to install GD extension.

**Comment by yuri25** [comment]
What exactly is the GD extension? I have php 7.4.2 hosting and the GD extension is installed. Please explain in more detail what and how to install.

**Comment by baijunyao** [comment]
You can check whether GD extension is enabled by `phpinfo()`;
```php
<?php

phpinfo();
```
![image](https://user-images.githubusercontent.com/9360694/75991067-d67ff380-5f30-11ea-8bbc-de8eb03a6069.png)

References:
1. https://www.cloudbooklet.com/install-php-7-4-on-ubuntu/
2. https://stackoverflow.com/questions/34367917/install-php70-gd-on-ubuntu

**Comment by yuri25** [comment]
Here I checked...
![php_gd](https://user-images.githubusercontent.com/253228/76019837-6c1c8280-5f33-11ea-9bb7-384b7a3e3c9c.jpg)

**Comment by baijunyao** [comment]
You are still missing `FreeType`.  
![image](https://user-images.githubusercontent.com/9360694/76081186-86ae3480-5fe3-11ea-810f-4c0786924edd.png)
References:
https://stackoverflow.com/questions/7290958/php-fatal-error-call-to-undefined-function-imagettftext

**Comment by yuri25** [comment]
I need to recompile php from source with support for these fonts. While I can’t succeed :(  Hosting support is stupid :)  If there is an opportunity, please help me.

**Comment by baijunyao** [comment]
OK, I have fixed it,  at the cost of not being able to add a watermark to the picture, you need to pull the latest code.

**Comment by yuri25** [comment]
Dear baijunyao, please undo the latest freetype related changes. Hosting support still helped solve the problem and now I have such a configuration.
![gd-2](https://user-images.githubusercontent.com/253228/76212590-e130d600-6219-11ea-8bd3-dbf604145a19.png)

**Comment by baijunyao** [comment]
Good, No need to revert commit for normal use.
