### ISSUE TITLE
执行php artisan bjyblog:install，报错了

### ISSUE THREAD

**Issue by michael7931** [baijunyao/laravel-bjyblog#14]
数据库账号密码都是对的

```In Connection.php line 664:  SQLSTATE[HY000] [1045] Access denied for user 'root'@'127.0.0.1' (using pas  sword: NO) (SQL: select * from information_schema.tables where table_schema   = blogdb and table_name = bjy_migrations)```

**Comment by baijunyao** [comment]
多谢反馈；已经修复；使用最新的代码看是否还有问题？

**Comment by baijunyao** [comment]
新代码没有问题的话；我先关闭了；有问题再打开哈；
