### ISSUE TITLE
手机前端，抽屉栏按钮点击报错，不显示

### ISSUE THREAD

**Issue by Kyourcn** [baijunyao/laravel-bjyblog#143]
TypeError: can't convert n to string app.js:1:227942
    test self-hosted:2737
    r http://blog.kyour.cn/js/app.js?id=4f47c574f6da2acfdfa2:1
    each http://blog.kyour.cn/js/app.js?id=4f47c574f6da2acfdfa2:1
    each http://blog.kyour.cn/js/app.js?id=4f47c574f6da2acfdfa2:1
    r http://blog.kyour.cn/js/app.js?id=4f47c574f6da2acfdfa2:1
    VSY+/</< http://blog.kyour.cn/js/app.js?id=4f47c574f6da2acfdfa2:1
    dispatch http://blog.kyour.cn/js/app.js?id=4f47c574f6da2acfdfa2:1
    handle http://blog.kyour.cn/js/app.js?id=4f47c574f6da2acfdfa2:1
    fireMouseEvent resource://devtools/server/actors/emulation/touch-simulator.js:312
    dispatchMouseEvents resource://devtools/server/actors/emulation/touch-simulator.js:287

**Comment by Kyourcn** [comment]
刚刚安装的，最新

**Comment by baijunyao** [comment]
多谢反馈； 是因为 jQuery 升级到 `3.5` 造成的； 已经修复了； 拉取最新代码即可；
