### ISSUE TITLE
Cannot get update ...

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#145]
` git pull
Update bbf803a1..c19bcb3b
error: Your local changes in the specified files will be overwritten during merging:
        .github/workflows/PHP-CS-Fixer.yml
        .github/workflows/PHP7.2+MySQL5.6.yml
        .github/workflows/PHP7.2+MySQL5.7.yml
        .github/workflows/PHP7.2+MySQL8.0.yml
        .github/workflows/PHP7.3+MySQL5.6.yml
        .github/workflows/PHP7.3+MySQL5.7.yml
        .github/workflows/PHP7.3+MySQL8.0.yml
        .github/workflows/PHP7.4+MySQL5.6.yml
        .github/workflows/PHP7.4+MySQL5.7.yml
        .github/workflows/PHP7.4+MySQL8.0.yml
        .github/workflows/PHPStan.yml
        .github/workflows/pull_request.yml
        .phpstorm.meta.php
        _ide_helper.php
        app/Console/Commands/Migration/FromThinkPHPBjyBlog.php
        app/Http/Controllers/Home/ArticleController.php
        app/Http/Controllers/Home/CategoryController.php
        app/Http/Controllers/Home/CommentController.php
        app/Http/Controllers/Home/FeedController.php
        app/Http/Controllers/Home/LikeController.php
        app/Http/Controllers/Home/NoteController.php
        app/Http/Controllers/Home/OpenSourceController.php
        app/Http/Controllers/Home/SiteController.php
        app/Http/Controllers/Home/SocialiteUserController.php
        app/Http/Controllers/Home/TagController.php
        app/Http/Controllers/Resources/ArticleController.php
        app/Http/Controllers/Resources/CommentController.php
        app/Http/Controllers/Resources/NoteController.php
        app/Http/Requests/Comment/Store.php
        app/Models/Comment.php
        app/Notifications/Comment.php
        app/Observers/CommentObserver.php
        app/Providers/ComposerServiceProvider.php
        composer.json
        composer.lock
        config/bjyblog.php
        database/migrations/2017_07_11_225347_create_comments_table.php
        database/seeds/CommentsTableSeeder.php
        database/seeds/ConfigsTableSeeder.php
        database/seeds/ConsolesTableSeeder.php
        package.json
        public/ant/asset-manifest.json
        public/ant/index.html
        public/ant/umi.7b53b784.js
        public/css/app.css
        public/js/admin.js
        public/js/app.js
        public/mix-manifest.json
        resources/js/home/comment.js
        resources/sass/home/index.scss
        resources/views/admin/article/create.blade.php
        resources/views/admin/article/edit.blade.php
        resources/views/admin/article/index.blade.php
        resources/views/admin/article/replaceView.blade.php
        resources/views/admin/category/create.blade.php
        resources/views/admin/category/edit.blade.php
        resources/views/admin/category/index.blade.php
        resources/views/admin/comment/edit.blade.php
        resources/views/admin/comment/index.blade.php
        resources/views/admin/comment/replaceView.blade.php
        resources/views/admin/config/backup.blade.php
        resources/views/admin/config/commentAudit.blade.php
        resources/views/admin/config/edit.blade.php
        resources/views/admin/config/email.blade.php
        resources/views/admin/config/licenses.blade.php
        resources/views/admin/config/qqQun.blade.php
        resources/views/admin/config/search.blade.php
        resources/views/admin/config/seo.blade.php
        resources/views/admin/config/socialLinks.blade.php
        resources/views/admin/config/socialShare.blade.php
        resources/views/admin/config/socialite.blade.php
        resources/views/admin/friendshipLink/create.blade.php
        resources/views/admin/friendshipLink/edit.blade.php
        resources/views/admin/friendshipLink/index.blade.php
        resources/views/admin/index/index.blade.php
        resources/views/admin/login/index.blade.php
        resources/views/admin/nav/create.blade.php
        resources/views/admin/nav/edit.blade.php
        resources/views/admin/nav/index.blade.php
        resources/views/admin/note/create.blade.php
        resources/views/admin/note/edit.blade.php
        resources/views/admin/note/index.blade.php
        resources/views/admin/openSource/create.blade.php
        resources/views/admin/openSource/edit.blade.php
        resources/views/admin/openSource/index.blade.php
        resources/views/admin/site/create.blade.php
        resources/views/admin/site/edit.blade.php
        resources/views/admin/site/index.blade.php
        resources/views/admin/socialiteClient/edit.blade.php
        resources/views/admin/socialiteClient/index.blade.php
        resources/views/admin/socialiteUser/edit.blade.php
        resources/views/admin/socialiteUser/index.blade.php
        resources/views/admin/tag/create.blade.php
        resources/views/admin/tag/edit.blade.php
        resour
Interrupt
`
Not so long ago, it was normally updated.
What can be done? Help me please.

**Comment by baijunyao** [comment]
Because the file you modified causes conflicts, you can view the conflicting files through the following commands. 

```
git status
git diff
```

You need to resolve the conflicts, or use the following command to overwrite the local changes.

```
git fetch --all
git reset --hard origin/master
```
The above command is dangerous, please check the usage of the above command.

Execute the upgrade command finally.

https://baijunyao.com/docs/laravel-bjyblog/en/Upgrade.html

**Comment by yuri25** [comment]
Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found

**Comment by baijunyao** [comment]
```
composer dump-autoload
```

**Comment by yuri25** [comment]
composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Package league/commonmark-ext-strikethrough is abandoned, you should avoid using it. Use league/commonmark instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Application.php line 690:

  Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by baijunyao** [comment]
Change your .env file


https://baijunyao.com/docs/laravel-bjyblog/en/DeployToProduction.html

**Comment by yuri25** [comment]
Sorry, I accidentally deleted the entire vendor folder; now I’ll completely restore the site from backup.
I'm not sure if it is worth updating later?

**Comment by yuri25** [comment]
Restored the site from backup. I tried to update again ...
`git pull
Из https://gitee.com/baijunyao/laravel-bjyblog
   bbf803a1..c19bcb3b  master                 -> origin/master
   7abe9ab3..c19bcb3b  develop                -> origin/develop
 + 84e27f54...fba111e2 feature/github-actions -> origin/feature/github-actions                                                                                                                                                               (принудительное обновление)
Обновление bbf803a1..c19bcb3b
error: Ваши локальные изменения в указанных файлах будут перезаписаны при слияни                                                                                                                                                             и:
        resources/views/errors/404.blade.php
Сделайте коммит или спрячьте ваши изменения перед слиянием веток.
error: Указанные неотслеживаемые файлы в рабочем каталоге будут перезаписаны при                                                                                                                                                              слиянии:
        .github/workflows/CI.yml
        .github/workflows/PR.yml
        app/Console/Commands/Translation/Sync.php
        app/Console/Commands/Upgrade/V10_0_0.php
        app/Console/Commands/Upgrade/V9_0_0.php
        app/Extensions/Illuminate/View/Factory.php
        app/Http/Controllers/Home/Controller.php
        public/ant/umi.f344afba.js
        resources/sass/github.scss
        resources/views/admin/layouts/admin.blade.php
        resources/views/admin/layouts/gentelella.blade.php
        resources/views/admin/vendor/.gitkeep
        resources/views/admin/vendor/pagination/bjypage.blade.php
        resources/views/blueberry/errors/404.blade.php
        resources/views/blueberry/errors/503.blade.php
        resources/views/blueberry/feed/atom.blade.php
        resources/views/blueberry/home/index/article.blade.php
        resources/views/blueberry/home/index/index.blade.php
        resources/views/blueberry/home/index/note.blade.php
        resources/views/blueberry/home/index/openSource.blade.php
        resources/views/blueberry/home/site/index.blade.php
        resources/views/blueberry/layouts/home.blade.php
        resources/views/blueberry/vendor/.gitkeep
        resources/views/blueberry/vendor/pagination/bjypage.blade.php
        tailwind.config.js
        tests/Commands/Upgrade/V10_0_0/CommandTest.php
        tests/Commands/Upgrade/V10_0_0/UpgradeTest.php
        tests/Commands/Upgrade/V10_0_0/migrations/2014_10_12_000000_create_users                                                                                                                                                             _table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2014_10_12_100000_create_passw                                                                                                                                                             ord_resets_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2016_06_01_000001_create_oauth                                                                                                                                                             _auth_codes_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2016_06_01_000002_create_oauth                                                                                                                                                             _access_tokens_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2016_06_01_000003_create_oauth                                                                                                                                                             _refresh_tokens_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2016_06_01_000004_create_oauth                                                                                                                                                             _clients_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2016_06_01_000005_create_oauth                                                                                                                                                             _personal_access_clients_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_artic                                                                                                                                                             le_tags_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_artic                                                                                                                                                             les_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_categ                                                                                                                                                             ories_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_comme                                                                                                                                                             nts_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_confi                                                                                                                                                             gs_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_frien                                                                                                                                                             dship_links_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_notes                                                                                                                                                             _table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_socia                                                                                                                                                             lite_users_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_07_11_225347_create_tags_                                                                                                                                                             table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_08_26_211441_create_jobs_                                                                                                                                                             table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_08_26_212556_create_faile                                                                                                                                                             d_jobs_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2017_10_18_203752_create_open_                                                                                                                                                             sources_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2018_06_29_032244_create_larav                                                                                                                                                             el_follow_tables.php
        tests/Commands/Upgrade/V10_0_0/migrations/2018_08_01_191920_create_navs_                                                                                                                                                             table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2018_09_04_204500_create_sites                                                                                                                                                             _table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2018_09_26_144126_create_conso                                                                                                                                                             les_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2019_05_07_225949_create_socia                                                                                                                                                             lite_clients_table.php
        tests/Commands/Upgrade/V10_0_0/migrations/2020_01_19_215118_create_artic                                                                                                                                                             le_histories_table.php
        tests/Commands/Upgrade/V10_0_0/seeds/ArticleTagsTableSeeder.php
        tests/Commands/Upgrade/V10_0_0/seeds/ArticlesTableSeeder.php
        tests/Commands/Upgrade/V10_0_0/seeds/CategoriesTableSeeder.php
        tests/Commands/Upgrade/V10_0_0/seeds/CommentsTableSeeder.php
        tests/Commands/Upgrade/V10_0_0/seeds/ConfigsTableSeeder.php
        tests/Commands/Upgrade/V10_0_0/seeds/ConsolesTableSeeder.php
        tests/Commands/Upgrade/V10_0_0/seeds/DatabaseSeeder.php
        tests/Commands/Upgrade/V10_0_
Прерываю
`
I can’t understand what’s the reason ... Previously, it was always updated normally without problems ... Why are there so many file inconsistencies?

**Comment by baijunyao** [comment]
I changed the folder directory to add themes, so there will be so many file changes.

**Comment by yuri25** [comment]
Ok, I will try to upgrade again.

**Comment by yuri25** [comment]
Installed a new version on a test site, I get this error when updating...
composer install --no-dev

`Package appstract/lush-http is abandoned, you should avoid using it. No replacement was suggested.
Package davejamesmiller/laravel-breadcrumbs is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
Package league/commonmark-ext-strikethrough is abandoned, you should avoid using it. Use league/commonmark instead.
Package league/commonmark-ext-table is abandoned, you should avoid using it. Use league/commonmark instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Application.php line 690:

  Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
`

**Comment by yuri25** [comment]
php artisan bjyblog:update

In Application.php line 690:

  Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found

**Comment by yuri25** [comment]
And I’m sorry, I forgot to exchange it for production.
