### ISSUE TITLE
Does not save changes in the settings in the admin panel

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#149]
In the admin panel, I change the language ... does not save the settings and produces the following error: 
419 | Page Expired
Installed as Production...If I change to local, some kind of error appears  
In Application.php line 690:

Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found

**Comment by yuri25** [comment]
It seems I understood ... it is necessary to establish at first as local .... and then already to develop and make changes for production ...

**Comment by baijunyao** [comment]
You can try in the following two ways:
1. Does the problem still exist with the new admin panel?  
![image](https://user-images.githubusercontent.com/9360694/84045385-4a6fe300-a9db-11ea-9dbe-df6c7dcd29dd.png)  
![image](https://user-images.githubusercontent.com/9360694/84046146-498b8100-a9dc-11ea-815d-98d4c7068e9a.png)  

2. Clean cache  
Execute the following command  
```
php artisan cache:clear
```
Clear browser cache  
![image](https://user-images.githubusercontent.com/9360694/84045913-03362200-a9dc-11ea-967e-4264458a2b9f.png)
