### ISSUE TITLE
Social login Error!!!

### ISSUE THREAD

**Issue by 34534206** [baijunyao/laravel-bjyblog#152]
Error in social login setting! 

![social](https://user-images.githubusercontent.com/66189342/87850552-d812ec80-c910-11ea-937d-4ec4da078a9a.png)

![invalid](https://user-images.githubusercontent.com/66189342/87850557-dd703700-c910-11ea-933f-6d008fb37ef8.png)

Do i have to pass "https://domain.com/auth/oauth/handleProviderCallback/facebook" in both "client id" and "client secret"?

OR  something different? I couldn't set up social login, i got invalid app id.

**Comment by baijunyao** [comment]
1. You need the client id (App ID) and client secret (App Secret), for example:
![image](https://user-images.githubusercontent.com/9360694/87851030-7ad66580-c927-11ea-826d-bc19cbf9ebfb.png)

2. And, you need to add redirect URL, for example:
![image](https://user-images.githubusercontent.com/9360694/87851011-524e6b80-c927-11ea-9fe4-a112d614c13f.png)

**Comment by 34534206** [comment]
Thank you for your help! Problem is fixed now.
