### ISSUE TITLE
新版后台进入有报错

### ISSUE THREAD

**Issue by lancer-wang** [baijunyao/laravel-bjyblog#158]
![image](https://user-images.githubusercontent.com/69783837/98211697-61f8cb00-1f7d-11eb-8548-870aae4cc6ce.png)

![image](https://user-images.githubusercontent.com/69783837/98211675-5907f980-1f7d-11eb-9a01-a5041af377a7.png)

似乎是第三方登录的问题

**Comment by baijunyao** [comment]
多谢提醒； 因为没有第三方登录的用户产生的提示； 我更新了一个 commit 去掉了这个弹框；拉取最新代码即可；

**Comment by lancer-wang** [comment]
解决了,3q
