### ISSUE TITLE
新版后台登录之前应该先在终端执行 php artisan passport:install

### ISSUE THREAD

**Issue by lancer-wang** [baijunyao/laravel-bjyblog#159]
不然后台登录不上,希望在教程中加上
![image](https://user-images.githubusercontent.com/69783837/98322422-557a7e00-2022-11eb-8ba4-c8439264844b.png)

**Comment by baijunyao** [comment]
多谢提醒； 已更新文档: [https://baijunyao.com/docs/laravel-bjyblog/安装.html](https://baijunyao.com/docs/laravel-bjyblog/安装.html)
