### ISSUE TITLE
文章编辑内容图片问题

### ISSUE THREAD

**Issue by hmx224** [baijunyao/laravel-bjyblog#167]
使用了早期的项目，近期发现文章中编辑图片，前端的组件出错：

Uncaught SyntaxError: Unexpected token 下 in JSON at position 131
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.uploadIframe.onload (image-dialog.js:161)

接口是已经上传图片成功，并返回了地址，我以为是版本问题，我从新下载了v14最新版，还有类似问题，求帮助

**Comment by baijunyao** [comment]
你用的什么浏览器？ 我在 Chrome 上没能重现这个问题； 方便截图看下吗？

**Comment by hmx224** [comment]
这个问题我出现过两次，我也是用的chrome浏览器，采用第三方qq登录到后台文章编辑，但是只要换个chrome的无痕模式就正常，错误信息图片如下：（主要是这个上传图片路径，没有加载到前端页面中）
![微信图片_20210322092721](https://user-images.githubusercontent.com/16735623/111929337-0b85c680-8af1-11eb-9987-ae9595b92605.png)
![微信图片_20210322092727](https://user-images.githubusercontent.com/16735623/111929339-0cb6f380-8af1-11eb-907c-250b906d1664.png)

**Comment by baijunyao** [comment]
无痕模式能稳定避开这个问题的话；可能会跟装的插件有关系；
另外再能触发这个错误的时候看下 chrome 的开发者工具中的 network 中的请求； 看看 response 是什么；可能错误信息就在 response 中；

**Comment by hmx224** [comment]
ok，thanks
