### ISSUE TITLE
网站貌似https下显示不完整

### ISSUE THREAD

**Issue by tangmingshuai** [baijunyao/laravel-bjyblog#17]
![image](https://user-images.githubusercontent.com/16934582/37241666-f2479792-2497-11e8-86af-5a247b997fe6.png)

**Comment by baijunyao** [comment]
应该是前端的 css 和 js 文件没加载成功； 配置虚拟主机的时候指定目录到 public 文件夹下了吗？

**Comment by tangmingshuai** [comment]
嗯，根目录设置在public文件夹了，目前http能够正常访问

**Comment by tangmingshuai** [comment]
是否应将js和css引用部分的代码需要更改为https？

**Comment by tangmingshuai** [comment]
已经解决了，在Providers\AppServiceProvider的boot方法中添加：

    \URL::forceScheme('https');
