### ISSUE TITLE
管理后台，点击升级报错。版本：v15.0.9

### ISSUE THREAD

**Issue by litao0501** [baijunyao/laravel-bjyblog#172]
![image](https://user-images.githubusercontent.com/15007186/119924244-cd4fcc00-bfa5-11eb-9235-4e862f2d5b8c.png)

> 正则匹配拿远程的版本，匹配空，报notice错。

**Comment by baijunyao** [comment]
多谢反馈；修复了哈；明天发新版后更新即可；
