### ISSUE TITLE
Update Menu

### ISSUE THREAD

**Issue by gejuking** [baijunyao/laravel-bjyblog#177]
Hello
This will more great if menu with multilevel, its so very difficult for me to modify from app.css file.

thanks you

**Comment by baijunyao** [comment]
Hello, 
[app.css](https://github.com/baijunyao/laravel-bjyblog/blob/v16.0.16/public/css/app.css) is built from [index.scss](https://github.com/baijunyao/laravel-bjyblog/blob/v16.0.16/resources/sass/home/index.scss), It is better to modify the [index.scss](https://github.com/baijunyao/laravel-bjyblog/blob/v16.0.16/resources/sass/home/index.scss), If you know how to use HTML and CSS, I can help you. 
I may support multi-level menus in the future, but it may take longer.

thanks

**Comment by gejuking** [comment]
oke, i will try. thanks
