### ISSUE TITLE
控制台报错，百度推送相关

### ISSUE THREAD

**Issue by tangmingshuai** [baijunyao/laravel-bjyblog#19]
![image](https://user-images.githubusercontent.com/16934582/37524092-c967b386-2963-11e8-9dd4-7f6e84daf8c7.png)
请问应该怎么解决

**Comment by baijunyao** [comment]
在外网环境把 百度统计、推送这些都换成 自己申请的 真实的 代码即可；

**Comment by tangmingshuai** [comment]
thks,更改后虽然还是报错但不影响推送和统计
btw,白老大的博客也报了错XD
![image](https://user-images.githubusercontent.com/16934582/37553074-7f2a173a-29fb-11e8-9167-0ab1ee537b1f.png)

**Comment by tangmingshuai** [comment]
检查发现是浏览器插件AdBlock的锅，它拦截了部分请求导致报错QAQ
