### ISSUE TITLE
关于bug的提醒

### ISSUE THREAD

**Issue by iningmeng** [baijunyao/laravel-bjyblog#2]
1.     categories表id字段没有设置自增长，而且里面挺多字段类型都是错的。
![_20170805112042](https://user-images.githubusercontent.com/18110319/28992486-20974e76-79d0-11e7-8485-990a469b0470.png)
2. 分类的排序方法只在路由注册了，没写对应的方法

**Comment by baijunyao** [comment]
多谢提醒；
1. migrations-generator 为了兼容；把 tinyint 转成 boolean 了；还顺便把自增主键给吃了；已手动修复；多谢提醒  
2. 排序方法已添加
