### ISSUE TITLE
后台访问地址是域名/admin吗？我的访问时404

### ISSUE THREAD

**Issue by yonnywei** [baijunyao/laravel-bjyblog#26]
![tim 20180812002446](https://user-images.githubusercontent.com/17950252/43994329-b9ee8d6a-9dcd-11e8-8745-a0a9cc6e70cc.png)

**Comment by baijunyao** [comment]
/admin/index/index  安装说明里面有哈 [开源项目系列之laravel-bjyblog博客](https://baijunyao.com/article/129)

**Comment by yonnywei** [comment]
多谢指点了，项目很赞
