### ISSUE TITLE
博客想使用邮件提醒，后台配置填写了相关参数，好像并未发送邮件，是不是配置文件里面还要填写配置呢？

### ISSUE THREAD

**Issue by yonnywei** [baijunyao/laravel-bjyblog#28]
![tim 20180817101756](https://user-images.githubusercontent.com/17950252/44244539-02307100-a207-11e8-9a45-ca9022ed1050.png)

**Comment by baijunyao** [comment]
是的；后台这个配置项是从旧版博客迁移过来的；发邮件的话暂时需要在 .env 中配置；我现在就解决这个问题；

**Comment by yonnywei** [comment]
好的

**Comment by baijunyao** [comment]
现在配置项已经都从数据库中读取了；不需要重复在 .env 配置了；下载最新版；或者旧版博客按照文档升级：https://baijunyao.com/docs/laravel-bjyblog/更新记录.html
