### ISSUE TITLE
小小建议：文章置顶了可以在前台标题标红或者加个置顶的角标

### ISSUE THREAD

**Issue by yonnywei** [baijunyao/laravel-bjyblog#29]
文章置顶了可以在前台标题颜色变成红色或者加个置顶的角标会更为突出显眼点，也好知道哪篇文章设置了置顶，仅代表个人意见

**Comment by baijunyao** [comment]
多谢建议；后续升级可以考虑加上；

**Comment by baijunyao** [comment]
置顶角标已经添加；效果如下： 
![](https://user-images.githubusercontent.com/9360694/46571491-7b974500-c9a8-11e8-87d9-597813427ff4.jpg)
