### ISSUE TITLE
正则匹配错误

### ISSUE THREAD

**Issue by iningmeng** [baijunyao/laravel-bjyblog#3]
好吧，还是我

文章提取图片的正则出错了，先上原来的代码和结果图：
![default](https://user-images.githubusercontent.com/18110319/28994150-065b062c-79fa-11e7-92e2-7b63703ed217.png)
![default](https://user-images.githubusercontent.com/18110319/28994151-067fb9ae-79fa-11e7-89d7-7f9c7e0d021b.png)
再来看修改后的结果图：
![default](https://user-images.githubusercontent.com/18110319/28994157-2259c99e-79fa-11e7-9c87-66608e4a8af0.png)
![default](https://user-images.githubusercontent.com/18110319/28994158-22a07164-79fa-11e7-9272-c5d035b10ef8.png)

**Comment by baijunyao** [comment]
之前没考虑图床图片的情况；已修复；多谢提醒；
