### ISSUE TITLE
使用语句更新项目后发现配置文件不见了

### ISSUE THREAD

**Issue by yonnywei** [baijunyao/laravel-bjyblog#33]
![tim 20181008173412](https://user-images.githubusercontent.com/17950252/46601886-2e8aae80-cb21-11e8-9988-78fbeb2d3ac5.jpg)

**Comment by baijunyao** [comment]
运行的哪个命令出的问题？ 你这个地方看不到 `.env` 应该是系统设置的不显示隐藏文件；因为根目录下不止 `.env` ；还有   
![image](https://user-images.githubusercontent.com/9360694/46774561-ab8e7180-cd35-11e8-9a4a-2c561a8038d5.png)
