### ISSUE TITLE
可以去掉底部的版权信息吗

### ISSUE THREAD

**Issue by pasawu** [baijunyao/laravel-bjyblog#34]
可以去掉底部的版权信息吗

**Comment by baijunyao** [comment]
可以；

**Comment by haizi1207060674** [comment]
兄弟 这个 为啥  不管是git svn 还是zip下载都是很慢   下载一半就断了

**Comment by baijunyao** [comment]
应该是网络的问题； 试试国内的代码库： [https://gitee.com/baijunyao/laravel-bjyblog](https://gitee.com/baijunyao/laravel-bjyblog)
