### ISSUE TITLE
安装项目时报错，求助

### ISSUE THREAD

**Issue by tangmingshuai** [baijunyao/laravel-bjyblog#35]
compact(): Undefined variable:  (View: /var/www/resources/views/home/index/index.blade.php)
按照文档中的步骤执行后，打开页面显示如上错误，求告知解决方法

**Comment by tangmingshuai** [comment]
查了下，应该是因为在PHP 7.3 中未设置的字符串不会被静默忽略。

**Comment by tangmingshuai** [comment]
嗯对，是compact()在7.3中的用法变更导致的

**Comment by baijunyao** [comment]
多谢提醒；我会在后期修复；

**Comment by baijunyao** [comment]
现在已经兼容 PHP7.3 了；
