### ISSUE TITLE
对楼主博客banner位的一点疑惑

### ISSUE THREAD

**Issue by CmderQ** [baijunyao/laravel-bjyblog#39]
![qq 20190207205838](https://user-images.githubusercontent.com/9278467/52412961-31bb9880-2b1b-11e9-8810-0f2027b74e9e.png)
想知道这个是博主这样设置的还是出现bug导致的？

**Comment by CmderQ** [comment]
画红框框的部分

**Comment by baijunyao** [comment]
故意这样设计的哈；并非 bug;

**Comment by CmderQ** [comment]
哈哈，有个性！正在看博主的开源项目，值得学习！
