### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#43]
Please, if possible, make a standard user registration. It is very difficult to register on graph.qq.com and weibo.com
With best regards!

**Comment by baijunyao** [comment]
Thank you for your issue, standard users are only for management, third-party users are used for comments, open standard user registration is difficult, I can add some international logins, such as Google, Facebook. 
With best regards!

**Comment by yuri25** [comment]
Thank you very much. Please add Google, Facebook and vk.com
Maybe the owner of this site will share :)  
https://www.snail-c.cn/
Although I certainly doubt it :)
With thanks!

**Comment by baijunyao** [comment]
Ok, I will add Google, Facebook, vk.com in the future release.

**Comment by yuri25** [comment]
Thank you very much!

**Comment by baijunyao** [comment]
I added google and facebook login, but I don't have a vk account, I can't receive the SMS verification code when registration vk account, you can pull requests or give me a vk test account.
![WX20190518-101747](https://user-images.githubusercontent.com/9360694/57964006-2967ca80-7960-11e9-93b7-bfb4a9f7440f.jpg)

**Comment by yuri25** [comment]
Thanks for the work. Maybe a little later I will give you a test account for vk.com
While I do not have the opportunity. Google and git configure it turned out - Facebook does not work: (

**Comment by yuri25** [comment]
Hi, I created a test temporary account on the VKontakte network. Here is the login information for your account:
username: +79515552028
password: cn981195

Then:
https://vk.com/dev/access_token
https://vk.com/dev/manuals

Or use the widget ....
https://vk.com/dev/Login
But the widget is probably not needed, it is better that all services are available and configured uniformly from the admin panel.

Write if you need anything else on my part. Thank.

**Comment by baijunyao** [comment]
Thank you for your VK account, I have already developed, you can change the VK password, I will merge to the master on 2019-07-06.  
<img width="1279" alt="QQ20190701-220606@2x" src="https://user-images.githubusercontent.com/9360694/60446657-69ef7f00-9c54-11e9-8b1a-ec4c79b9259b.png">  
The Facebook I tested is working. Can you take a screenshot to see the error message?

**Comment by yuri25** [comment]
Thank you!  I will try to work with facebook. Maybe I'm setting something up incorrectly when setting up the application in Facebook itself. If I can not solve the problem - I will send a screenshot.

**Comment by baijunyao** [comment]
v5.8.8.0 has been released, you can upgrade. [https://baijunyao.com/docs/laravel-bjyblog/en/Upgrade.html](https://baijunyao.com/docs/laravel-bjyblog/en/Upgrade.html)
