### ISSUE TITLE
comment popup empty

### ISSUE THREAD

**Issue by khyoz** [baijunyao/laravel-bjyblog#47]
When I try to create a comment, I have a popup but no choice for connexion anymore

![empty screen when trying to connect for comment](https://user-images.githubusercontent.com/26684951/57985259-a0d35200-7a65-11e9-997a-eebc4611a16c.png)

This is what I have on your blog and what I got a few days ago

![comment your blog](https://user-images.githubusercontent.com/26684951/57985286-f0198280-7a65-11e9-8bb3-78a799e5949b.png)

**Comment by baijunyao** [comment]
You need to add config;   [https://baijunyao.com/docs/laravel-bjyblog/en/OAuth.html](https://baijunyao.com/docs/laravel-bjyblog/en/OAuth.html)
