### ISSUE TITLE
Production : migrate error

### ISSUE THREAD

**Issue by khyoz** [baijunyao/laravel-bjyblog#60]
I try to install in production on CentOS 7
When I run : php artisan migrate
I have an error message : 

> In DuskServiceProvider.php line 43:
> 
>   It is unsafe to run Dusk in production.

in my .env file I have set 
> APP_ENV=production

**Comment by khyoz** [comment]
> composer install --no-dev
then
> composer dump-autoload
solved the issue

**Comment by baijunyao** [comment]
Yes,  https://baijunyao.com/docs/laravel-bjyblog/en/DeployToProduction.html
