### ISSUE TITLE
Problem after connexion with Facebook

### ISSUE THREAD

**Issue by khyoz** [baijunyao/laravel-bjyblog#61]
Hello, once I'm connected with Facebook when I try fo fill the comment, or fill the mail address field, I'm redirected to the home page...
Is there something more to configure ?
 
![bug-comment-2019-06-11_141530](https://user-images.githubusercontent.com/26684951/59280015-34630180-8c65-11e9-96c6-4b409e107f57.png)

Thanks for support.

**Comment by khyoz** [comment]
ok, my copyright signature got a 
`<a href="https://linktomywebsite">`  tag, and then the html code was rendered with some additional href tags, I removed it from config / copyright signature and I was able to access the fields.

**Comment by baijunyao** [comment]
Ok, I reproduced this problem, maybe I need to modify the code, it would be better to use markdown.
