### ISSUE TITLE
Article content appears in the article description field.

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#62]
When editing an article, the content - the article content is for some reason duplicated in the article description field. Is this how it should be?

![image](https://user-images.githubusercontent.com/253228/59570112-c7ec6600-909b-11e9-88d6-f80dd58cdcd5.png)

**Comment by baijunyao** [comment]
If the description is empty, intercept the first 300 words of the article content.

**Comment by yuri25** [comment]
When creating an article, I enter in the description field some kind of small description text. This text is less than 300 characters. Then, if I edit the article, the description text disappears and the text is taken from the content of the article instead. The description must necessarily be more than 300 characters?

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/59635726-8e2e6480-915a-11e9-84a9-92bb6fd33b8d.png)

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/59635881-e7969380-915a-11e9-854b-e52ee4f5f05c.png)

**Comment by yuri25** [comment]
Edit article

![image](https://user-images.githubusercontent.com/253228/59636019-35130080-915b-11e9-9474-6148fd487639.png)

**Comment by yuri25** [comment]
Here entered the article description...

![image](https://user-images.githubusercontent.com/253228/59636321-e2861400-915b-11e9-81e0-fa2d08974938.png)

**Comment by yuri25** [comment]
Type of article without a description ....

![image](https://user-images.githubusercontent.com/253228/59636496-53c5c700-915c-11e9-95be-3d374b6d28b8.png)

**Comment by yuri25** [comment]
Introduced a description of more than 300 characters - does not work correctly, instead of the description inserts the contents of the article ....

**Comment by baijunyao** [comment]
Thanks, I fixed this bug.

**Comment by baijunyao** [comment]
@all-contributors please add @shukunwang for bug

**Comment by baijunyao** [comment]
@all-contributors please add @yuri25 for bug
