### ISSUE TITLE
Emoji does not appear on the site.

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#63]
In the Emoji editor from git are not displayed. It is necessary to replace the path to the pictures in the files editormd.js and editormd.min.js
Replace this URL emoji-cheat-sheet.com with such URL
webfx.com/tools/emoji-cheat-sheet
After this replacement, images from Emoji github appear in the editor.
Nevertheless, when editing the article - on the right, these Emoji I observe. However, when publishing an article, only text is visible on the site, images of eiuji are absent: (

![image](https://user-images.githubusercontent.com/253228/59570200-f585df00-909c-11e9-9e84-9d486424ee52.png)

![image](https://user-images.githubusercontent.com/253228/59570201-0c2c3600-909d-11e9-83c7-61f049379bee.png)

**Comment by baijunyao** [comment]
Thanks for the feedback, I will fix this.
