### ISSUE TITLE
I can't figure out how chat works

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#64]
I understand this is a chat for one administrator? Because authorized users can not answer anything in the chat .... It’s rather the admin notes - I understand correctly? Who are the chat participants?

**Comment by baijunyao** [comment]
> It’s rather the admin notes  

Yes, `chat` for short statements, maybe using `chat` as the name is not very good.

**Comment by yuri25** [comment]
Good. In this case, I will rename the chat to admin notes or just quotes. Thanks for the answer.

**Comment by baijunyao** [comment]
Thanks for your suggestion, I will use note instead of chat.
