### ISSUE TITLE
How to get the rights on the site or what username and password to specify?

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#67]
Composer install
====================
- Installing symfony/filesystem (v4.3.2): Downloading (0%)
 Failed, trying the next URL (403: Invalid credentials for 'https://dl.laravel-china.org/symfony/filesystem/b9896d034463ad6fd2bf17e2bf9418caecd6313d.zip', aborting.)Loading from cache
====================
How to solve a problem?

**Comment by baijunyao** [comment]
I have removed the laravel-china.org mirrors in the develop branch and I will merge develop into master tomorrow. Before tomorrow, you can use `composer install --prefer-dist` to solve this problem.

**Comment by yuri25** [comment]
Thank you very much!
