### ISSUE TITLE
Question about music and video

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#69]
Could you add the ability to the editor to add music as a mp3 file and embed the video from the YouTube service? Thank.

**Comment by baijunyao** [comment]
Yes, you are welcome.

**Comment by baijunyao** [comment]
Youtube video is supported.
![1](https://user-images.githubusercontent.com/9360694/61164887-3530d100-a54c-11e9-98ae-33253d3121f9.png)
![2](https://user-images.githubusercontent.com/9360694/61164900-58f41700-a54c-11e9-8dee-c996b840e801.png)
![3](https://user-images.githubusercontent.com/9360694/61164902-5d203480-a54c-11e9-942d-525616931982.png)
![4](https://user-images.githubusercontent.com/9360694/61164903-601b2500-a54c-11e9-9479-c50e338c1d55.png)

**Comment by yuri25** [comment]
What about downloading mp3?

**Comment by baijunyao** [comment]
You can add HTML tags.  

video
```
<video width="320" height="240" controls>
  <source src="https://www.w3schools.com/tags/movie.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>
```
audio
```
<audio src="http://www.w3school.com.cn/i/horse.ogg" controls="controls">
Your browser does not support the audio element.
</audio>
```

<img width="696" alt="7" src="https://user-images.githubusercontent.com/9360694/61217992-8820a900-a743-11e9-8ce9-d4c4216b8b0a.png">

<img width="643" alt="8" src="https://user-images.githubusercontent.com/9360694/61218011-940c6b00-a743-11e9-8470-451bce64297b.png">

**Comment by yuri25** [comment]
Thank you very much! Great job and great blog!
