### ISSUE TITLE
Login social via facebook can not configure:(

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#70]
I can’t configure my Facebook login. Please help me set this up.

![image](https://user-images.githubusercontent.com/253228/60769066-37baa300-a0d4-11e9-8995-b5c62bf7dd48.png)

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/60769146-0098c180-a0d5-11e9-9cd2-c09da33e32e7.png)

**Comment by baijunyao** [comment]
It seems that you need to set the URL, the following is my settings, you can use as a reference.

![image](https://user-images.githubusercontent.com/9360694/60769407-d6112d80-a101-11e9-9fa8-37bc3e988b7f.png)

![image](https://user-images.githubusercontent.com/9360694/60769413-ecb78480-a101-11e9-8bfa-fa63559923e1.png)

![image](https://user-images.githubusercontent.com/9360694/60769457-7c5d3300-a102-11e9-8b61-74708a55884b.png)

![image](https://user-images.githubusercontent.com/9360694/60769465-aca4d180-a102-11e9-9e5e-b38a6a5b36a1.png)

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/60769749-4f962500-a0dc-11e9-9013-3d795700a43c.png)

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/60769767-82d8b400-a0dc-11e9-99bd-c3c6cd6f5c59.png)

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/60769781-a00d8280-a0dc-11e9-858c-b21d08a93fe2.png)

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/60769806-d814c580-a0dc-11e9-8905-722a1d68aabb.png)

**Comment by yuri25** [comment]
What is wrong with me?

**Comment by baijunyao** [comment]
The URL is wrong and should be `https://ptzmedia.ru/auth/oauth/handleProviderCallback/facebook` .  
`feacebook` => `facebook`.  
![image](https://user-images.githubusercontent.com/9360694/60770055-7585ee80-a109-11e9-9df2-0bcdd918e349.png)

![image](https://user-images.githubusercontent.com/9360694/60770061-85053780-a109-11e9-8b56-2c660ba1062d.png)

**Comment by yuri25** [comment]
This is where I copied and corrected only the domain :)) 
https://baijunyao.com/docs/laravel-bjyblog/en/OAuth.html
Thank you very much!

**Comment by baijunyao** [comment]
:joy:  Sorry, I'll modify the document immediately.

**Comment by yuri25** [comment]
Now everything works!  Thank you!
