### ISSUE TITLE
Comment hangs after clicking on "Submit"

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#71]
Comment hangs after clicking on "Submit"
Here is this image
https://ptzmedia.ru/statics/layer-2.4/skin/default/loading-1.gif

If you refresh the page - a comment appears in its place.

**Comment by baijunyao** [comment]
Maybe the reason for not configuring the mail, I fixed the code, you try to pull the latest code, if it still does not work, send the log in the `storage/logs/` directory to me to see the specific reasons, thank you.

**Comment by yuri25** [comment]
I updated - git pull. 
Now comments are published immediately. Thank you very much!

**Comment by baijunyao** [comment]
Sentry issue: [LARAVEL-BJYBLOG-1C](https://sentry.io/organizations/baijunyao/issues/1111350730/?referrer=github_plugin)
