### ISSUE TITLE
About translation - Question

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#73]
Can you please tell me how to add another language to the system? And in what files you need to change for this? I want to try to translate into Russian. Thank.

**Comment by baijunyao** [comment]
Thank you!  
You need to translate the two files below.  
1. https://github.com/baijunyao/laravel-bjyblog/blob/feature/ISSUE-73-russian-translate/resources/lang/ru.json
<img width="1013" alt="9" src="https://user-images.githubusercontent.com/9360694/62299340-59c2fd80-b4a7-11e9-87f4-b8ff6bfc0c36.png">
<img width="919" alt="8" src="https://user-images.githubusercontent.com/9360694/62299352-5f204800-b4a7-11e9-8bae-85c62481b949.png">

2. https://github.com/baijunyao/laravel-bjyblog/blob/feature/ISSUE-73-russian-translate/resources/lang/ru/others.php  
Do not modify the following html tag.  
`<span class="b-highlight">:word</span>`  
`<span class="b-highlight">:tag</span>`  
`<span class="b-highlight">:count</span>`

**Comment by yuri25** [comment]
I will do this soon. Thank you very much!

**Comment by yuri25** [comment]
I made changes to translate into Russian. Check, please. When I see the translation on my test site, something may need to be changed. Thank you very much!

**Comment by yuri25** [comment]
Unfortunately, I am not good at working with git ... Please help if I can’t do everything right.

**Comment by baijunyao** [comment]
Good job! Thank you very much!

**Comment by yuri25** [comment]
Hello. What are my next steps?

**Comment by baijunyao** [comment]
You have not to do anything, I will merge the code into the master branch at 2019-08-10.

**Comment by yuri25** [comment]
Thank you very much!

**Comment by baijunyao** [comment]
The new version has been released, you can upgrade it.  
 [https://baijunyao.com/docs/laravel-bjyblog/en/Upgrade.html](https://baijunyao.com/docs/laravel-bjyblog/en/Upgrade.html)
