### ISSUE TITLE
统计缓存有问题

### ISSUE THREAD

**Issue by 327100395** [baijunyao/laravel-bjyblog#76]
所有统计都是1的，看了统计的代码好像只有读缓存，没有写缓存的操作

**Comment by 327100395** [comment]
统计的缓存只有等缓存过期了才更新的吗

**Comment by baijunyao** [comment]
写操作的缓存在这清理了； https://github.com/baijunyao/laravel-bjyblog/blob/master/app/Observers/BaseObserver.php

**Comment by baijunyao** [comment]
现在使用了 [genealabs/laravel-model-caching](http://github.com/genealabs/laravel-model-caching) 扩展包来自动缓存； 不需要写清理的代码了；  
https://github.com/baijunyao/laravel-bjyblog/commit/536d04e877d428ebe6614397b68b29637e1dd964
