### ISSUE TITLE
An error occurred after deleting the article

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#78]
An error occurred after deleting the article
http://xtty.ru/admin/article/forceDelete/2

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'AlgoliaSearch\Version' not found

The record is erroneous, please close it.

**Comment by yuri25** [comment]
Although I'm not sure ... such an error appeared when publishing the article:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'AlgoliaSearch\Version' not found

**Comment by yuri25** [comment]
All the same, there is a mistake.  
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'AlgoliaSearch\Version' not found
Points to this place....
`  public function createAlgoliaDriver()
    {
        AlgoliaUserAgent::addSuffixUserAgentSegment('Laravel Scout', '3.0.10');
 
        return new AlgoliaEngine(new Algolia(
            config('scout.algolia.id'), config('scout.algolia.secret')
        ));
    }`

1. "Class 'AlgoliaSearch\Version' not found"

**Comment by baijunyao** [comment]
What is the value of `SCOUT_DRIVER` in your *.env* file?  
Have you deleted the `SCOUT_DRIVER` or changed the value of `SCOUT_DRIVER` to `algolia`?  
Changing the value of `SCOUT_DRIVER` to `null` will solve this error;
https://github.com/baijunyao/laravel-bjyblog/blob/master/.env.example#L36

**Comment by yuri25** [comment]
There were problems associated with the change of hosting. I had all the default settings
SCOUT_DRIVER = null
I am sorry. Please close this issue.

**Comment by baijunyao** [comment]
It's ok.
