### ISSUE TITLE
Words in notes are not torn according to the rules. A possible solution is not to break words, but to transfer the whole to a new line.

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#79]
Hello. Is it possible to prohibit word breaks and transfer them as a whole if they do not fit on a line. And then in the notes it looks ugly in Russian and in English too ... I would be grateful if you solve this problem.

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/63303033-5f15aa00-c2e7-11e9-9396-8fbaf806e84f.png)

**Comment by baijunyao** [comment]
Thanks! I have fixed it, Pull the latest code.

**Comment by yuri25** [comment]
I updated [my site](https://xtty.ru/note) and now everything works correctly.
Great job! Thank you very much!

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/63376416-6d6ecf00-c396-11e9-834d-8503ec170a8a.png)

![image](https://user-images.githubusercontent.com/253228/63376458-85dee980-c396-11e9-9998-caf1b96313ee.png)

**Comment by baijunyao** [comment]
OK, I have fixed it.

**Comment by yuri25** [comment]
Great job! Thank you very much!
