### ISSUE TITLE
Add to translation into other languages

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#84]
In file `/app/Http/Controllers/Home/SiteController.php`
Hard spelled:
```
 $head = [
            'title'       => '推荐博客',
            'keywords'    => '推荐博客',
            'description' => '推荐博客',
```
-----------------------------------------
```
 return ajax_return(200, '提交成功');
        } else {
            return ajax_return(400, '提交失败');
        }
```
Please include this in translations into other languages. And it would be very good that these parameters could be set in the admin panel.
Although there is an SEO item in the admin panel ... how to understand?
I follow the link https://xtty.ru/site in the browser tab, I see  this word 推荐 博客 - Мой блог

**Comment by yuri25** [comment]
Also, please include in the translation of the word in the modal window when adding the site this:

```
申请 (请确保已添加本站的友情链接)
名称 --> 请输入网站名
链接 --> 请输入URL
描述 --> 请输入博客描述
邮箱 --> 请输入邮箱用于接收通知
```

**Comment by baijunyao** [comment]
Ok, I will do this later, thanks.

**Comment by baijunyao** [comment]
I use Google Translate, If it is incorrect, you can open a `Pull Request`.  
https://github.com/baijunyao/laravel-bjyblog/commit/4a4e208e37ccd9248596969c43d5733ce7d4e69e#diff-dc937f2a2c4c225fbf9475910520258b

**Comment by yuri25** [comment]
The revised version is better to do so:
"Submitted successfully, waiting for approve.": "Отправлено успешно, ожидайте подтверждения",

    "Success": "Успешно",
    "Fail": "Неудачно",
    "Apply": "Применить",
    "URL": "URL",
    "Site Name": "Название сайта",
    "Please add a friendly link to this site": "Пожалуйста, добавьте дружественную ссылку на этот сайт"

**Comment by baijunyao** [comment]
Thank you, I am done.
