### ISSUE TITLE
Sites (recommended blogs) that users add do not appear in the admin panel.

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#85]
If the user adds a blog, a message appears that everything is successful .... However, the recommended blog (site) does not appear in the admin panel after that. I am authorized by the administrator and I do not see the blog, which as administrator I have to approve or delete. Please help solve the problem.

**Comment by baijunyao** [comment]
Do you want to let the `recommend blog` is approved when added a `recommend blog` in the admin panel?

**Comment by yuri25** [comment]
As an example, I added the test site https://ptzportal.ru on your blog https://baijunyao.com Check please.

**Comment by baijunyao** [comment]
I received an email notification and I have already approved.

**Comment by yuri25** [comment]
And in the admin panel the site automatically appears and you just click the "Approve" button? Or do you take the data from the letter and manually in the admin panel then add the site as an administrator? I don’t understand this moment.

**Comment by baijunyao** [comment]
Just click the "Approve" button.  
![image](https://user-images.githubusercontent.com/9360694/64861450-8cdddc80-d662-11e9-805a-5e5c85bafe4c.png)

**Comment by yuri25** [comment]
On my site https://xtty.ru it also worked out. I don’t know why it wasn’t added before ... Excuse me for your time.

**Comment by baijunyao** [comment]
Never mind.
