### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#89]
php artisan bjyblog:update

 

> In PhpRedisConnector.php line 72:
>  Please remove or rename the Redis facade alias in your "app" configuration
>  file in order to avoid collision with the PHP Redis extension.

I searched and found here:
https://github.com/laravel/horizon/issues/659

> 1 Replace in config\app.php
> aliasess:
> 'Redis' => Illuminate\Support\Facades\Redis::class,
> for:
> 'RedisManager' => Illuminate\Support\Facades\Redis::class,
> 
> 2 Replace in config\database.php
> 
> 'redis' => [
> 
>     'client' => env('REDIS_CLIENT', 'predis'), //default phpredis
>     ...

I checked with myself - it works. Perhaps you will find a better solution and fix the problem as you think best.

**Comment by baijunyao** [comment]
Thanks, I fixed it.
