### ISSUE TITLE
Some commands lead to errors

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#90]
php artisan optimize

> Configuration cache cleared!
> Configuration cached successfully!
> Route cache cleared!
> 
> In Route.php line 917:
> 
>   Unable to prepare route [api/user] for serialization. Uses Closure.
> 

php artisan route:cache

> Route cache cleared!
> 
> In Route.php line 917:
> 
>   Unable to prepare route [api/user] for serialization. Uses Closure.
> 

Also authorization via google has stopped working. Because of this, I can not log in as administrator. It produces such a 500 | server error. Other social login services work fine. Take a look and fix it please.

I see this in the logs:
production.ERROR: Call to undefined function SocialiteProviders\Google\array_get() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function SocialiteProviders\\Google\\array_get() at /............/xtty.ru/vendor/socialiteproviders/google/Provider.php:69)

**Comment by baijunyao** [comment]
Thanks, I fixed it.
