### ISSUE TITLE
Is it possible to? sitemap and robots.txt

### ISSUE THREAD

**Issue by yuri25** [baijunyao/laravel-bjyblog#91]
A big request, please, if possible, add something to your project to generate a site map and normal use of sitemaps and robots.txt file.
I found several solutions on the network, but on my own I do not dare to install, I am afraid to ruin everything. Please look like a professional.
https://github.com/Laravelium/laravel-sitemap
https://github.com/spatie/laravel-sitemap
https://github.com/digitaldreams/laravel-seo-tools
If this is implemented, then the project will be much better perceived by search engines.
A third option would be great.
Thank you for your work.

**Comment by baijunyao** [comment]
Thanks for your suggestion, I chose [laravel-sitemap](https://github.com/spatie/laravel-sitemap), you can pull the latest code to experience this feature, If you have any questions, feel free to tell me , I will improve it in the future. By the way, If you want to add code, don't worry about writing errors, I will fix it for you.

**Comment by baijunyao** [comment]
Thanks for your suggestion, you can pull the latest code to experience this feature, If you have any questions, feel free to tell me, I will improve it in the future. By the way, If you want to add code, don't worry about writing errors, I will fix it for you.

**Comment by yuri25** [comment]
Great job! Thank you very much for implementing this opportunity. I updated my site, the sitemap is working, no errors have been noticed so far.
